```{r}
library(rgenoud)
library(Matching)
```

```{r}
foo <- read.csv(url("https://course-resources.minerva.kgi.edu/uploaded_files/mke/00089202-1711/daughters.csv"))
head(foo)
```
```{r}
model <- lm(nowtot ~ Dems + Repubs + Christian + age + srvlng + demvote + hasgirls, data = foo)
summary(model)
```
```{r}
confint(model)
```
```{r}
model_new <- lm(nowtot ~ Repubs + Christian + demvote + hasgirls, data = foo)
summary(model_new)
```
```{r}
confint(model_new)
```
```{r}
# Check balance of the unmatched set
mb <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote, data = foo)
```
```{r}
set.seed(2324)
genout <- GenMatch(Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), pop.size = 20, nboots = 250)
mout <- Match(Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), Weight.matrix = genout)
mb_after <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote, data = foo, match.out = mout)
```
```{r}
genout_withM2 <- GenMatch(Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), pop.size = 20, nboots = 250, M = 2)
mout_withM2 <- Match(Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), Weight.matrix = genout_withM2, M = 2)
mb_withM2 <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote, data = foo, match.out = mout_withM2)

```
```{r}
genout_withM3 <- GenMatch(Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), pop.size = 20, nboots = 250, M = 3)
mout_withM3 <- Match(Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), Weight.matrix = genout_withM3, M = 3)
mb_withM3 <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote, data = foo, match.out = mout_withM3)
```
```{r}
mout_withY <- Match(Y = foo$nowtot, Tr = foo$hasgirls, X = cbind(foo$Dems, foo$Repubs, foo$Christian, foo$age, foo$srvlng, foo$demvote), Weight.matrix = genout)
mb_withY <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote, data = foo, match.out = mout_withY)
```
```{r}
summary(mout_withY)
```
```{r}
lower_bound = mout_withY$est - 1.96 * mout_withY$se
upper_bound = mout_withY$est + 1.96 * mout_withY$se
cat("The 95% confidence interval of the average treatment effect is [", lower_bound, "," ,upper_bound, "]")
```
PART B:

```{r}
foo <- read.csv(url("https://course-resources.minerva.kgi.edu/uploaded_files/mke/00089202-1711/daughters.csv"))
foo_treat <- subset(foo, foo$ngirls >= 2 & foo$nboys == 0)
foo_control <- subset(foo, foo$nboys >= 2 & foo$ngirls == 0)

foo2 <- rbind(foo_treat, foo_control)

dim(foo2)
```

```{r}
model2 <- lm(nowtot ~ Dems + Repubs + Christian + age + srvlng + demvote + hasgirls, data = foo2)
summary(model2)
```
```{r}
confint(model2)
```

```{r}
set.seed(2324)
genout2 <- GenMatch(Tr = foo2$hasgirls, X = cbind(foo2$Dems, foo2$Repubs, foo2$Christian, foo2$age, foo2$srvlng, foo2$demvote), pop.size = 20, nboots = 250)
mout2 <- Match(Y=foo2$nowtot, Tr = foo2$hasgirls, X = cbind(foo2$Dems, foo2$Repubs, foo2$Christian, foo2$age, foo2$srvlng, foo2$demvote), Weight.matrix = genout2)
mb_after2 <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote, data = foo2, match.out = mout2)
```
```{r}
summary(mout2)
```

```{r}
lower_bound2 = mout2$est - 1.96 * mout2$se
upper_bound2 = mout2$est + 1.96 * mout2$se
cat("The 95% confidence interval of the average treatment effect is [", lower_bound2, "," ,upper_bound2, "]")
```
```{r}
genout2_specified <- GenMatch(Tr = foo2$hasgirls, X = cbind(foo2$Dems, foo2$Repubs, foo2$Christian, foo2$age, foo2$srvlng, foo2$demvote, foo2$white, foo2$female), pop.size = 20, nboots = 250)
mout2_specified <- Match(Y=foo2$nowtot, Tr = foo2$hasgirls, X = cbind(foo2$Dems, foo2$Repubs, foo2$Christian, foo2$age, foo2$srvlng, foo2$demvote, foo2$white, foo2$female), Weight.matrix = genout2_specified)
mb_after2_specified <- MatchBalance(hasgirls ~ Dems + Repubs + Christian + age + srvlng + demvote + female + white, data = foo2, match.out = mout2_specified)
```
```{r}
summary(mout2_specified)
```
```{r}
lower_bound2_specified = mout2_specified$est - 1.96 * mout2_specified$se
upper_bound2_specified = mout2_specified$est + 1.96 * mout2_specified$se
cat("The 95% confidence interval of the average treatment effect is [", lower_bound2_specified, "," ,upper_bound2_specified, "]")
```

QUESTION 2

```{r}


library(rgenoud)

library(date)
library(Matching)

rm(list=ls())
foo <- read.csv("Downloads/district - district.csv")

#dim(foo)
#76772   14

missing_bank_code <- rep(0, 76772)
missing_bank_name <- rep(0, 76772)
missing_date_of_birth <- rep(0, 76772)
NA_district_code <- rep(0, 76772)
NA_capital <- rep(0, 76772)
NA_credit_proposal <- rep(0, 76772)

foo <- cbind(foo, missing_bank_code,
             missing_bank_name,
             missing_date_of_birth,
             NA_district_code,
             NA_capital,
             NA_credit_proposal)

foo$missing_bank_code[which(foo$bank_code == "")] <- 1
foo$missing_bank_name[which(foo$bank_name == "")] <- 1
foo$missing_date_of_birth[which(foo$date_of_birth == "")] <- 1
foo$NA_capital[which(is.na(foo$capital) == TRUE)] <- 1
foo$NA_credit_proposal[which(is.na(foo$credit_proposal) == TRUE)] <- 1
foo$NA_district_code[which(is.na(foo$district_code) == TRUE)] <- 1

#change the dates to R-readable format
foo$R_date_of_birth <- as.character(foo[,3])
for(i in 1:length(foo[,3])) {foo$R_date_of_birth[i] <- as.date(foo$R_date_of_birth[i], order = 
                                                                 "dmy")}
foo$R_date_of_birth <- as.date(as.numeric(foo$R_date_of_birth))

oldest <- which(foo$R_date_of_birth < as.date("1-Jan-1910"))
youngest <- which(foo$R_date_of_birth > as.date("1 Jan 2001"))

foo$oldest <- rep(0, length(foo[,3]))
foo$youngest <- rep(0, length(foo[,3]))
foo$outlier_ages <- rep(0, length(foo[,3]))
foo$oldest[oldest] <- 1
foo$youngest[youngest] <- 1
foo$outlier_ages[c(oldest,youngest)] <- 1
foo$R_date_of_birth[which(is.na(foo$R_date_of_birth) == TRUE)] <- -9999999

#standard deviation
SD <- 365/sd(foo$R_date_of_birth)
# 0.000305876

#this obs with specific postal code makes no sense
#foo <- foo[-which(foo$postal_code == 9151), ]

#to extract only the first 2 digits of district codes:
foo$district_code1 <- foo$district_code%/% 100
foo$district_code1[which(is.na(foo$district_code1) == TRUE)] <- -9999999

#credit_proposal feature engineering
foo$credit_proposal[which(is.na(foo$credit_proposal) == TRUE)] <- 9999999

foo$credit_proposal_0 <- foo$credit_proposal == 0 & (is.na(foo$credit_proposal) == FALSE)
foo$credit_proposal_0to5 <- foo$credit_proposal > 0 & foo$credit_proposal < 5000000 & 
  (is.na(foo$credit_proposal) == FALSE)
foo$credit_proposal_5to10 <- foo$credit_proposal >= 5000000 & foo$credit_proposal < 10000000 & 
  (is.na(foo$credit_proposal) == FALSE)
foo$credit_proposal_10to20 <- foo$credit_proposal >= 10000000 & foo$credit_proposal < 20000000 & 
  (is.na(foo$credit_proposal) == FALSE)
foo$credit_proposal_20up <- foo$credit_proposal >= 20000000 & (is.na(foo$credit_proposal) == 
                                                                 FALSE)

foo$credit_proposal_transformed <-
  1*foo$credit_proposal_0 +
  2*foo$credit_proposal_0to5 +
  3*foo$credit_proposal_5to10 +
  4*foo$credit_proposal_10to20 +
  5*foo$credit_proposal_20up +
  6*foo$NA_credit_proposal

#NA capital
foo$capital[which(is.na(foo$capital) == TRUE)] <- 9999999

#capital feature engineering
foo$capital_0 <- foo$capital == 0 & (is.na(foo$capital) == FALSE)
foo$capital_0to2 <- foo$capital > 0 & foo$capital < 200000 & (is.na(foo$capital) == FALSE)
foo$capital_2to5 <- foo$capital >= 200000 & foo$capital < 500000 & (is.na(foo$capital) == FALSE)
foo$capital_5to10 <- foo$capital >= 500000 & foo$capital < 1000000 & (is.na(foo$capital) == 
                                                                        FALSE)
foo$capital_10to20 <- foo$capital >= 1000000 & foo$capital < 2000000 & (is.na(foo$capital) == 
                                                                          FALSE)
foo$capital_20to50 <- foo$capital >= 2000000 & foo$capital < 5000000 & (is.na(foo$capital) == 
                                                                          FALSE)
foo$capital_50up <- foo$capital >= 5000000 & (is.na(foo$capital) == FALSE)
foo$capital_transformed <-
  1*foo$capital_0 +
  2*foo$capital_0to2 +
  3*foo$capital_2to5 +
  4*foo$capital_5to10 +
  5*foo$capital_10to20 +
  6*foo$capital_20to50 +
  7*foo$capital_50up +
  8*foo$NA_capital

#worker feature engineering
#remove outlier in the control group (10 million workers)
foo <- foo[-which(foo$worker == max(foo$worker)),]

foo$worker_0 <- foo$worker == 0
foo$worker_1 <- foo$worker == 1
foo$worker_2 <- foo$worker == 2
foo$worker_3 <- foo$worker == 3
foo$worker_4 <- foo$worker == 4
foo$worker_5to9 <- foo$worker >=5 & foo$worker < 10
foo$worker_10to24 <- foo$worker >=10 & foo$worker < 25
foo$worker_25to99 <- foo$worker >=25 & foo$worker < 100
foo$worker_100up <- foo$worker >= 100

foo$worker_transformed <-
  1*foo$worker_0 +
  2*foo$worker_1 +
  3*foo$worker_2 +
  4*foo$worker_3 +
  5*foo$worker_4 +
  6*foo$worker_5to9 +
  7*foo$worker_10to24 +
  8*foo$worker_25to99 +
  9*foo$worker_100up

#treatment Indicator
foo$treat <- foo$status == "Sudah"

#the only bank code (var 1) is PEM
#the only bank name (var 2) is PEMDA -- regional government, not a bank
#(var 3) 174 outlier ages
#(var 4) gender is 3 levels: men, women, and business entity ("LAKI-LAKI" "PEREMPUAN" "BADAN USAHA")
#(var 5) marital_status: business agency, single, married ("BADAN USAHA" "BELUM KAWIN" "KAWIN")

###(var 6) EDUCATION
#"BADAN USAHA" "DIPLOMA" "LAINNYA" "SARJANA" "SD"  "SMP" "SMU"
#"BUSINESS AGENCY" "DIPLOMA" "OTHER" "GRADUATE" "Elementary School" "Middle School" "High School"

###(var 7) OCCUPATION
#[1]"KARYAWAN SWASTA"  "LAIN-LAIN/BADAN USAHA"  "NELAYAN"  "PEDAGANG"              
#[5]"PENSIUNAN/PURNAWIRAWAN" "PETANI"  "PNS" "PROFESIONAL"          
#[9]"TNI/POLRI"  "WIRASWASTA"      

#[1]"PRIVATE EMPLOYEES" [2] "OTHERS / BUSINESS AGENCIES" [3] "FISHERMANS" [4] "TRADERS"
#[5]"PENSIONERS / PURNAWIRAWAN" [6] "FARMERS" [7] "CIVIL SERVANT" [8] "PROFESSIONAL"
#[9]"ARMY / POLICE" [10] "ENTREPRENEURS"

###(var 8) 938 unique POSTAL CODES

###(var 9) 63 unique DISTRICT CODES

###(var 10) : "worker". unknown meaning... 300+ unique numerical values (maybe no. of staff?)

### (var 11) (capital)
# 0%      25%      50%      75%     100%
# 0.00e+00 1.00e+06 1.00e+07 1.50e+07 1.75e+11

###(var 12) (credit proposal)
#0%     25%     50%     75%    100%
#0.0e+00 0.0e+00 1.0e+07 2.5e+07 5.0e+09

###(var 13) STATUS
#"Belum"    "Sudah"
#"Not Yet"  "Already"

###(var 14) randomid

foo_badan <- foo[which(foo$gender == "BADAN USAHA"), ]
foo_people <- foo[-which(foo$gender == "BADAN USAHA"), ]


```

```{r}
######## CODE MODIFICATION ########

X = data.frame(foo$R_date_of_birth, foo$district_code1,
                foo$worker, foo$capital, foo$credit_proposal,
                foo$worker_transformed, foo$capital_transformed, foo$credit_proposal_transformed,
                foo$missing_date_of_birth,
                foo$NA_district_code,
                foo$NA_capital,
                foo$NA_credit_proposal)


Tr <- foo$treat

BalanceMat <- X

genout <- GenMatch(Tr=Tr, X=X, BalanceMatrix=BalanceMat, estimand="ATT", M=1,
                   pop.size=5, max.generations=2, wait.generations=1,
                   caliper = c(0.000305876,1e+16,
                               1e+16,1e+16,1e+16,
                               1e+16,1e+16,1e+16,
                               1e+16,
                               1e+16,
                               1e+16,
                               1e+16),
                   exact = c(FALSE, TRUE,
                             FALSE, FALSE, FALSE,
                             TRUE, TRUE, TRUE,
                             TRUE,
                             TRUE,
                             TRUE,
                             TRUE))

mout <- Match(Tr=Tr, X=X, estimand="ATT", M=1,
              exact = c(FALSE, TRUE,
                        FALSE, FALSE, FALSE,
                        TRUE, TRUE, TRUE,
                        TRUE, 
                        TRUE, 
                        TRUE, 
                        TRUE),
              caliper = c(0.000305876, 1e+16,
                          1e+16,1e+16,1e+16,
                          1e+16,1e+16,1e+16,
                          1e+16,
                          1e+16,
                          1e+16,
                          1e+16),
              Weight.matrix = genout)
                   

summary(mout)

mb <- MatchBalance(foo$treat~
                            	foo$R_date_of_birth + foo$district_code1 +
                            	foo$worker + foo$capital + foo$credit_proposal +
                            	foo$worker_transformed + foo$capital_transformed + 
                              foo$credit_proposal_transformed +
                            	foo$missing_date_of_birth +
                            	foo$NA_district_code +
                            	foo$NA_capital +
                            	foo$NA_credit_proposal,
                            	match.out=mout, nboots=500)
```










